version: '3.4'

services:
  backendengineerassessmentmain:
    image: backendengineerassessmentmain
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
